name: 'Render website'
description: 'Render dita-ot/docs into dita-ot/website'
inputs:
  WEBSITE_PLUGIN_BRANCH:
    description: 'Website plug-in ref'
    default: 'master'
  DITA_OT_VERSION:
    description: 'DITA-OT version used for rendering'
    default: '3.6.1'
  SRC_DITA_OT_VERSION:
    description: 'DITA-OT version used as source'
    required: true
runs:
  using: 'composite'
  steps:
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Set Node.js version 12.x
      uses: actions/setup-node@v1
      with:
        node-version: 12.x

    - name: Download website plug-in
      shell: bash
      run: |
        curl -sL https://github.com/dita-ot/org.dita-ot.html/archive/refs/heads/${{ inputs.WEBSITE_PLUGIN_BRANCH }}.zip -o org.dita-ot.html.zip
    - name: Cache stable DITA-OT
      uses: actions/cache@v2
      with:
        path: dita-ot-${{ inputs.DITA_OT_VERSION }}
        key: ${{ runner.os }}-dita-ot-${{ inputs.DITA_OT_VERSION }}

    - name: Download stable DITA-OT
      shell: bash
      run: |
        if [ ! -d "dita-ot-${{ inputs.DITA_OT_VERSION }}" ]; then
          curl -sL https://github.com/dita-ot/dita-ot/releases/download/${{ inputs.DITA_OT_VERSION }}/dita-ot-${{ inputs.DITA_OT_VERSION }}.zip -o dita-ot-${{ inputs.DITA_OT_VERSION }}.zip
          unzip dita-ot-${{ inputs.DITA_OT_VERSION }}.zip
        else
          echo "Use cached dita-ot-${{ inputs.DITA_OT_VERSION }}"
        fi
        dita-ot-${{ inputs.DITA_OT_VERSION }}/bin/dita install org.dita-ot.html.zip --force -v

    - name: Download source DITA-OT
      shell: bash
      run: |
        curl -sL https://github.com/dita-ot/dita-ot/releases/download/${{ inputs.SRC_DITA_OT_VERSION }}/dita-ot-${{ inputs.SRC_DITA_OT_VERSION }}.zip -o dita-ot-${{ inputs.SRC_DITA_OT_VERSION }}.zip
        unzip dita-ot-${{ inputs.SRC_DITA_OT_VERSION }}.zip -d src-dita-ot
        src-dita-ot/dita-ot-${{ inputs.SRC_DITA_OT_VERSION }}/bin/dita install org.dita-ot.html.zip --force -v
        echo "DITA_OT_DEV=src-dita-ot/dita-ot-${{ inputs.SRC_DITA_OT_VERSION }}" >> $GITHUB_ENV

    - name: Run DITA-OT
      shell: bash
      run: |
        VS=($(echo $VERSION | tr '.' ' '))
        RELEASE=$VS[1].$VS[2]
        ./gradlew site \
          -PditaHome=${{ github.workspace }}/dita-ot-${{ inputs.DITA_OT_VERSION }} \
          -PoutputDir=${{ github.workspace }}/website/$RELEASE \
          -PditaHomeSrc=${{ env.DITA_OT_DEV }} \
          -PnoCommitMeta=true \
          --info --stacktrace --no-daemon
      env:
        VERSION: ${{ inputs.SRC_DITA_OT_VERSION }}
