# This workflow will build PR changes and push to website repo

name: DITA-OT CI for website preview

on:
  pull_request:
    branches: [ develop ]
    types: [ opened, synchronize, reopened ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout docs
      uses: actions/checkout@v2
    - name: Checkout website
      uses: actions/checkout@v2
      with:
        repository: dita-ot/website
        path: website
    
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Set Node.js version 12.x
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - name: Set up Netflify 
      uses: actions/checkout@master

    
    - name: Download stable DITA-OT
      run: |
        curl -L https://github.com/dita-ot/dita-ot/releases/download/3.5.1/dita-ot-3.5.1.zip -o dita-ot-3.5.1.zip
        unzip dita-ot-3.5.1.zip
        dita-ot-3.5.1/bin/dita install https://github.com/dita-ot/org.dita-ot.html/archive/master.zip -v
        
    - name: Download develop DITA-OT
      run: |
        curl -L https://s3-eu-west-1.amazonaws.com/dita-ot/dita-ot-develop.zip -o dita-ot-develop.zip
        unzip dita-ot-develop.zip        
        
    - name: Run DITA-OT
      run: |
        export DITA_OT_DEV=$(find $PWD -name 'dita-ot-*+*' -type d | head -1)
        ./gradlew site -PditaHome=dita-ot-3.5.1 -PoutputDir=website/dev -PditaHomeSrc=${DITA_OT_DEV} --info --stacktrace --no-daemon

    - name: Deploy to Netlify
      uses: netlify/actions/cli@master
      with:
        args: deploy --dir website --alias "preview/${{ env.GITHUB_REF }}"
      env:
        NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
