# This workflow will build PR changes and push to website repo

#sudo: false
#language: java
#jdk:
#- openjdk8
#env:
#   global:
#   - DITA_OT_VERSION=3.5.1
# install:
# - ".travis/install.sh"
# script:
# - ".travis/publish.sh"
# after_success:
# - ".travis/deploy.sh"


name: DITA-OT Java CI for Website preview

on:
  pull_request:
    branches: [ deploy ]
    types: [ opened, synchronize, reopened ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout docs
      uses: actions/checkout@v2
      with:
        path: docs
    - name: Checkout website
      uses: actions/checkout@v2
      with:
        repository: dita-ot/website
        path: website
    
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Set Node.js version 12.x
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - run: curl -L https://github.com/dita-ot/dita-ot/releases/download/3.5.1/dita-ot-3.5.1.zip -o dita-ot-3.5.1.zip
    - run: unzip dita-ot-3.5.1.zip
    - run: dita-ot-3.5.1/bin/dita

#    - name: Grant execute permission for gradlew
#      run: chmod +x gradlew
    
#    - name: Build with Gradle
#      run: ./gradlew build
