# This workflow builds changes to release tag and commits to website repo for release PR

name: Debug generate website release PR

on:
  workflow_dispatch:
    inputs:
      dita-ot-version:
        description: 'DITA-OT version'
        required: true
      docs-tag:
        description: 'Docs tag'
        required: true
  repository_dispatch:
    types: [release]

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      WEBSITE_PLUGIN_BRANCH: 'master'
      DITA_OT_VERSION: '4.0.1'
    steps:
      - name: Get arguments
        run: |
          if [[ -z "${{ github.event.client_payload.dita_ot_version }}" ]]; then
            readonly TOKENS=($(echo "${{ github.event.client_payload.dita_ot_version }}" | tr '.' ' '))
          else
            readonly TOKENS=($(echo "${{ github.event.inputs.dita-ot-version }}" | tr '.' ' '))
          fi
          echo "RELEASE=${TOKENS[0]}.${TOKENS[1]}" >> $GITHUB_ENV
          if [[ -z "${{ github.event.client_payload.docs_tag }}" ]]; then
            echo "TAG=${{ github.event.client_payload.docs_tag }}" >> $GITHUB_ENV
          else
            echo "TAG=${{ github.event.inputs.docs-tag }}" >> $GITHUB_ENV
          fi
      - name: Check out docs
        uses: actions/checkout@v3
        with:
          ref: ${{ env.TAG }}
      - name: Get variables
        run: |
          echo "GITHUB_SHA_SHORT=$(git rev-parse --short HEAD)" >> $GITHUB_ENV
      - name: Debug
        run: |
          echo "${{ env.TAG }}"
          echo "${{ env.RELEASE }}"
          echo "${{ env.GITHUB_SHA_SHORT }}"
